# Generated by Django 5.2.9 on 2025-12-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, choices=[('Black', 'Black'), ('Blue', 'Blue'), ('Red', 'Red'), ('White', 'White'), ('Green', 'Green'), ('Brown', 'Brown'), ('Beige', 'Beige'), ('Yellow', 'Yellow'), ('Pink', 'Pink')], help_text='Primary product color used for AI recommendations', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='color',
            field=models.CharField(choices=[('Black', 'Black'), ('Blue', 'Blue'), ('Red', 'Red'), ('White', 'White'), ('Green', 'Green'), ('Brown', 'Brown'), ('Beige', 'Beige'), ('Yellow', 'Yellow'), ('Pink', 'Pink')], max_length=20),
        ),
    ]
