# Generated by Django 5.2.9 on 2025-12-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_color_alter_productvariant_color'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'size')},
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.CharField(choices=[('S', 'S / 38'), ('M', 'M / 40'), ('L', 'L / 42'), ('XL', 'XL / 44')], max_length=5),
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='color',
        ),
    ]
