# Generated by Django 5.2.9 on 2025-12-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_productvariant_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original price before AI adjustment', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='cart_add_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='current_demand_score',
            field=models.IntegerField(default=50, help_text='0-100 score. 50 is neutral.'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_dynamic_pricing',
            field=models.BooleanField(default=False, help_text='Enable AI-driven price adjustments'),
        ),
        migrations.AddField(
            model_name='product',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
