# Generated by Django 5.2.9 on 2025-12-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_base_price_product_cart_add_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='units_sold',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
