# Generated by Django 5.2.9 on 2025-12-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_units_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_dynamic_pricing',
            field=models.BooleanField(default=True, help_text='Enable AI-driven price adjustments'),
        ),
    ]
