# Generated by Django 5.2.9 on 2025-12-31 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_is_dynamic_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.TextField(blank=True, help_text="AI-generated tags (e.g., 'Shirt, Red, Casual')"),
        ),
    ]
