# Generated by Django 5.2.9 on 2026-03-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_max_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_flagged_spam',
            field=models.BooleanField(default=False, help_text='Flagged by heuristic spam detection for short length or repeated words'),
        ),
        migrations.AddField(
            model_name='review',
            name='sentiment_polarity',
            field=models.FloatField(blank=True, help_text='TextBlob Polarity: -1.0 (Negative) to +1.0 (Positive)', null=True),
        ),
    ]
