# Generated by Django 5.2.9 on 2025-12-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderitem_color_orderitem_ssize'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='ssize',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(default='NA', max_length=5),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='color',
            field=models.CharField(default='Unknown', max_length=20),
        ),
    ]
